### ISSUE TITLE
Run coffeepod errors

### ISSUE THREAD

**Issue by Zitzeronion** [DLR-RY/TwoPhaseFlow#21]
Tried to run the Allrun script for the coffeePod case in the of2112 branch, and encountered a foam fatal io error.

The log file is attached the issue seems to be the heRhoThermo type.
[logmultiRegionPhaseChangeFlow.txt](https://github.com/DLR-RY/TwoPhaseFlow/files/8049442/logmultiRegionPhaseChangeFlow.txt)

In the master branch of1812 this error does not appear.

**Comment by HenningScheufler** [comment]
The made changes to the thermodynamic model in version v2112. You have to chose a different thermomodel. Tabulatedthermo does not compile with the new thermodynanic model
