### ISSUE TITLE
Solution singularity (Benchmark problem: Sucking Interface Problem)

### ISSUE THREAD

**Issue by Bumble-7** [DLR-RY/TwoPhaseFlow#22]
Dear Authors,
I downloaded the recent version of code and tried to run the benchmark cases. The 1D sucking interface problem throws the error "DILUPBiCGStab:  Solving for Ux:  solution singularity". I am attaching the setup files below.

https://github.com/Bumble-7/Benchmark_simulations

Thank you

**Comment by Bumble-7** [comment]
Is it possible for someone to comment on this issue?

**Comment by HenningScheufler** [comment]
Have you tried the smoothSolver instead of PBiCGStab?

**Comment by Bumble-7** [comment]
Thanks for the response. I haven't actually, let me try. I just executed the benchmark case by running Allrun file. So it ran considering the parameters which are already present in the files.

**Comment by Bumble-7** [comment]
The problem is solved using the smoothSolver. Thank you for the clarification. I have an additional doubt regarding the initAlphaFieldDict. Even though the alpha.water is set in the setFieldsDict file explicitly, is it necessary to run the initAlphaFieldDict? I see that if I skip initAlphaFieldDict, the interface actually doesn't move. There is also a gradual variation of the alpha if I use it. Will the solver won't work if we have a discontinuous alpha field?

Kindly request you to shed light on the same. Thank you

**Comment by HenningScheufler** [comment]
The phasechange mass flow needs a surface area and the interface is only calculated in the cells with a value smaller 1 or larger zero. So if you use setFields. It will not find an interface so nothing happens

**Comment by Bumble-7** [comment]
Ok, I understand now. Thanks again for your time.
