### ISSUE TITLE
dynamic contact angle model

### ISSUE THREAD

**Issue by senlinq** [DLR-RY/TwoPhaseFlow#23]
Is there any _documentation or reference_ for **dynamic contact angle model** implemented so far?

**Comment by HenningScheufler** [comment]
Sadly no but its based on VoxVoinov and Jiang relation.

The implementation is very old from my first days as Phd and needs some improvements

**Comment by senlinq** [comment]
> Sadly no but its based on VoxVoinov and Jiang relation.
> 
> The implementation is very old from my first days as Phd and needs some improvements

Thanks, I found some articles related to the model you implemented. 

But I think your implementation is great, and I might be able to contribute some dynamic contact angle model **based on your code template**. So what are _the parts you mentioned that need improvement_?

**Comment by HenningScheufler** [comment]
Its mainly the code quality. 

There is no need to have two boundary conditions for compressible and incompressible. They are identical except how they get the data nu, rho, mu, sigma etc. 

Both of these are available in twoPhaseModelThermo, immiscibleIncompressibleTwoPhaseMixture or the turbulence model.

For debugging purposes it might be useful create a new field contactAngle. Have a look at the wallHeatFlux postProcessing functions.

**Comment by senlinq** [comment]
Thanks a lot. I wil try to get get through the points you mentioned above.
