### ISSUE TITLE
Three phase line 

### ISSUE THREAD

**Issue by Bumble-7** [DLR-RY/TwoPhaseFlow#26]
Dear Authors,
This is not an issue but I don't know other platforms to convey the same. I am interested in knowing how the interaction between solid and fluid is accounted for in the calculations. I was unable to understand the same from the given information in the paper and I apologize for it. Basically, I am looking at how the three-phase line is treated. Mainly, how the attractive force between solid and liquid/interface is captured. This is one of the important aspects of the bubble departure simulations. I kindly request someone to comment on the same thing. 

Thank you

**Comment by Bumble-7** [comment]
I am sorry to bother you again. Could someone comment on this query? I am very new to multiphase modeling from the numerical simulations side. 

Thank you

**Comment by HenningScheufler** [comment]
Contact angle models describe the three-phase contact line. Currently, only static and dynamic contact angles are available
