### ISSUE TITLE
Obsolete initAlphaFieldDict

### ISSUE THREAD

**Issue by HenrikSontheimer** [DLR-RY/TwoPhaseFlow#3]
The `initAlphaFieldDict` stored in the apps/initAlphaField/ folder is obsolete. `composedFunction` should be used instead of `composedFunctions` and `type` instead of `function`, i.e. `type sphere`.

**Comment by HenningScheufler** [comment]
closed in commit 2b32da1fa0b2884b838e6323c476dfd818c4a08d
