### ISSUE TITLE
interface capturing in 3D unstructured mesh

### ISSUE THREAD

**Issue by Bumble-7** [DLR-RY/TwoPhaseFlow#36]
Dear Authors,
I am using multiRegionPhaseChangeFlow to simulate liquid water phase change. I was able to simulate the bubble growth problem in a structured grid. For an unstructured grid, the simulation works fine for 2D but not for 3D. I am attaching the images for both cases for reference. I went through a couple of threads in the forum regarding general comments on unstructured grids. It seems that there might be necessary to change a few schemes and fvsolution options. If any work was done using unstructured mesh, could someone share their feedback? It would be helpful to prevent the rediscovery of suitable schemes. I am attaching the fvschemes and fvsolution that I am using. 

tetra mesh (3d)
https://github.com/Bumble-7/bubble_growth/blob/main/tetra.PNG

hexa mesh (3d)
https://github.com/Bumble-7/bubble_growth/blob/main/hex.PNG

tetra mesh (2d)
https://github.com/Bumble-7/bubble_growth/blob/main/tetra_2d.PNG

fvschemes
https://github.com/Bumble-7/bubble_growth/blob/main/fvSchemes

fvsolutions
https://github.com/Bumble-7/bubble_growth/blob/main/fvSolution

Thank you

**Comment by Bumble-7** [comment]
Hi,
I have tried running the tetrahedral mesh with more suitable fvschemes options suggested in a couple of threads. There is some improvement in the interface but is still far from the structured mesh results. I am attaching the forum threads on the tetrahedral mesh schemes. 

https://www.cfd-online.com/Forums/openfoam-solving/82696-convergence-problem-tetrahedral-grids.html#post285857
https://www.cfd-online.com/Forums/openfoam-meshing/75572-openfoam-structured-unstructured-grids.html

Could someone let me know if such problems have been seen before?

Thank you

**Comment by HenningScheufler** [comment]
Try without the nOuterCorrectors
