### ISSUE TITLE
After using "interFlow -overwrite" to refine the mesh, "topoSet and createPatch" will not work

### ISSUE THREAD

**Issue by Mkhydrogen** [DLR-RY/TwoPhaseFlow#42]
Hello, Henning
At the beginning, I planned to use SHM to refinemesh first and then use topoSet and createPatch to extract an inlet for forming an inlet patch, but, the snapptHexMeshDict conflict with LoadBalance, to the best of my test.
So,how to use "topoSet and createPatch" with "interFlow -overwrite" correctly, emm... or another method to achieve this function
thx!

**Comment by HenningScheufler** [comment]
Sadly, AMR does not work with Snappy has only hex cells can be split. In order to use AMR you need to build a structured mesh
