### ISSUE TITLE
Absence of alpha*Dp/dt term in TLEqn

### ISSUE THREAD

**Issue by Bumble-7** [DLR-RY/TwoPhaseFlow#43]
I noticed that alpha*Dp/dt is missing from the TLEqn whereas it has been correctly added to TVEqn. Is there any reason to remove it from the liquid phase? I have attached a snip from the code. Please let me know if I have missed any detail. 

![image](https://github.com/DLR-RY/TwoPhaseFlow/assets/93425678/95d89d76-8af9-487b-85ed-7165e9710db8)

Additionally, the KappaLEFF usually should be equal to alpha*k. When I print the values, it is just k in the interface cells. Could you confirm if it has been ignored, as the heat transfer between the phases is handled separately?

Thank you

**Comment by Bumble-7** [comment]
Could anyone help with how the volume fraction equation in the documentation has been derived? It looks slightly different than the conventional equation (attaching a snip here). Mainly the one of the alpha source term is not visible. I am trying to understand the formulation it will be of great help to get the guidance. 

![image](https://github.com/DLR-RY/TwoPhaseFlow/assets/93425678/16e3d03b-3535-4837-9005-0901fe6f52b8)

**Comment by HenningScheufler** [comment]
> Is there any reason to remove it from the liquid phase?

the liquid phase is assumed incompressible. But i plan to switch to a internal energy formulation
