### ISSUE TITLE
Parasitic currents due to surface tension at microscale 

### ISSUE THREAD

**Issue by Bumble-7** [DLR-RY/TwoPhaseFlow#44]
I am trying to simulate the growth of very small bubble. The initial size of the bubble is 10-30 micron. I see that the bubble just moves randomly in the domain during the simulation which is not observed for the larger bubbles. On further observation, it was clear that the parasitic velocities are larger on the micro-scale and might be the reason for the destabilization of the bubble. I have tried refining the mesh but doesn't help. Could you please let me know if such behavior is expected at small scales and is there a way to resolve this?

Additionally, in order to minimize the parasitic currents, I have changed the curvature calculation models. It looks like the gradAlpha model is giving good results out of all. The simulation consists of a 60-micron bubble in the middle of the liquid. The domain size is 300 x 600 micron with an axis-symmetric geometry. The gravity is absent, and no phase change. I am attaching the images of the bubble location after 0.5 ms. 

![curvature_models](https://github.com/DLR-RY/TwoPhaseFlow/assets/93425678/883655dd-64e0-4e65-ac1f-28abbea575ac)

Thank you

**Comment by Bumble-7** [comment]
Hi,
I tried using a more accurate discretization scheme for RDF, and the results get a bit better but still the instability of the bubbles exists. I am confused about where to look for the solution. Is it possible for anyone to show the direction? Ideally, plicRDF with RDF curvature calculation should lead to more accurate results. Is there any problem with simulations at very small length scales?

**Comment by HenningScheufler** [comment]
The current state of the art curvature models don't converge with mesh refinement. So, you can expect that the parasitic currents increase for smaller bubble sizes. 
One of the aims of this library is that people can easily add new more accurate surface tension models to mitigate the problems associated with small scale bubbles.

Could you share the input files?

**Comment by Bumble-7** [comment]
Thanks for the response. I am attaching the input files (run.bat file has the commands used to run the simulation). 

Input files:
https://github.com/Bumble-7/bubble_growth/tree/main/stationary_bubble

So is there a way to find if the current curvature model is accurate enough to use for a specific bubble size? 

Thank you

**Comment by Bumble-7** [comment]
Here is a relevant paper regarding accurate surface tension modeling. 
https://arxiv.org/pdf/2005.02865.pdf

**Comment by HenningScheufler** [comment]
The current height function implementation is not compatible with wedges.

**Comment by Bumble-7** [comment]
Thanks for the response. I agree that the height function method works better in the 3D setup. I ran the same stationary bubble simulation in the 3D using symmetry plane boundary conditions; the results are much better but still not perfect. I also tried MULES with the gradAlpha curvature model and it also gives good results for the stationary bubble. However, due to the symmetry of the problem, the bubble does not gets destabilized, and I see the magnitude of currents is still the same. 

I want to ask one last query as I explore different options. Is there any combination, for example, MULES with gradAlpha with specific gradschemes and reconstruction schemes, that would work for small-scale bubbles? 

Thank you in advance

**Comment by Bumble-7** [comment]
Dear Henning, 
I did a quick check using interIsoFoam if it could simulate the stationary bubble at low-length scales. The bubble is stable and does not deform or translate. I am trying to understand where the complexity arising in the present solver due to which the interface is unstable. Would you be able to comment on this? 

Thank you

**Comment by Bumble-7** [comment]
Dear Henning,
I am trying different methods available in the literature to reduce the parasitic currents at micron scale (100 micron bubble diameter). But I am not able to succeed. Is it possible to reduce the drafts by any means at that scale? I have tried smoothening the alpha filed and the computing the curvature using smoothened alpha field. I will be really glad to know if there is any good combination which might work to reduce the parasitic currents at micron scale. 

@HenningScheufler 

Thank you
