### ISSUE TITLE
multiRegionPhaseChangeFlow -overwrite not solving any solving any fields

### ISSUE THREAD

**Issue by MitchellWhiting** [DLR-RY/TwoPhaseFlow#45]
Good Day, 

I am attempting to run multiRegionPhaseChangeFlow with AMR, I use the -overwrite option so that the mesh actually updates (otherwise I get an MPI error), and when I do then none of my fields solve. I have pasted a full solver iteration below. I am not sure what I need to do. 
Thank you in advance.
/---------------------------------------------------------------------------------------------------------------------------/
Solving for fluid region fluid
Reading thermophysical properties

--> FOAM Warning : 
    From Foam::entry* Foam::dictionary::add(Foam::entry*, bool)
    in file db/dictionary/dictionary.C at line 777
    Reading "/.../processor0/system/fluid/data"
    Attempt to add entry finalIteration which already exists in dictionary "/.../processor0/system/fluid/data"
Time = 8.929920734e-10

Selected 68 cells for refinement out of 62500.
Refined from 62500 to 62704 cells.
Selected 0 split edges out of a possible 68.
Maximum imbalance = 2.857871906 %
Execution time for mesh.update() = 0.15 s

Solving for solid region solid
--> FOAM Warning : 
    From Foam::entry* Foam::dictionary::add(Foam::entry*, bool)
    in file db/dictionary/dictionary.C at line 777
    Reading "/.../processor0/system/fluid/data"
    Attempt to add entry finalIteration which already exists in dictionary "/.../processor0/system/fluid/data"
ExecutionTime = 5.35 s  ClockTime = 9 s

Interface Courant Number mean: 0 max: 0
Region: fluid Courant Number mean: 0 max: 0
Capillary Number: 0.004648416416
Region: solid Diffusion Number mean: 7.265721654e-05 max: 0.08593756718
deltaT = 2.9859838e-10
Time = 1.191590453e-09
/---------------------------------------------------------------------------------------------------------------------------/

**Comment by MitchellWhiting** [comment]
It is worth mentioning I am on OpenFOAM v2106, using the v2106 TwoPhaseFlow distribution with the v2012 multiDimAMR distribution and I'm not certain I correctly compiled the multiDimAMR library, I got a bit confused with the different versions and am not adept at using github yet.
Here is the case that is failing:
[Dynamic_clean.zip](https://github.com/DLR-RY/TwoPhaseFlow/files/12337361/Dynamic_clean.zip)
Again, thank you in advance.

**Comment by HenningScheufler** [comment]
Sadly, the implementation of the AMR libary does not allow to reconstruct and redistribute the mesh.

To view the results you need to:

1.  touch test.foam (only the file extension foam matters) 
2. start paraview and open the .foam file
3.  select the decomposed case.

The overwrite option allows you to simulate just one timestep and overwrite the current mesh within the timestep. This way you more accurately set the alpha field e.g.
refineInterval  1; <-- needs to be 1 
runApplication decomposePar -allRegions
runParallel -s 1 initAlphaField -region fluid
runParallel -s 1 multiRegionPhaseChangeFlow -overwrite
runParallel -s 2 initAlphaField -region fluid
runParallel -s 2 multiRegionPhaseChangeFlow -overwrite
runParallel -s 3 initAlphaField -region fluid
runParallel -s 3 multiRegionPhaseChangeFlow -overwrite
runParallel -s 4 initAlphaField -region fluid
refineInterval  1; <-- set to a different value (have a look at foamDictionary)
runParallel -s final multiRegionPhaseChangeFlow

**Comment by MitchellWhiting** [comment]
Thank you for the reply, that is initialization advice. However, I run into an error when I try to run multiRegionPhaseChangeFlow without "-overwrite" and I've been unable to find a solution to it. Whenever my solver reaches the refinement step it crashes with this output:

Execution time for mesh.update() = 0.48 s
[panos5:503587] *** An error occurred in MPI_Waitall
[panos5:503587] *** reported by process [2770075649,1]
[panos5:503587] *** on communicator MPI_COMM_WORLD
[panos5:503587] *** MPI_ERR_TRUNCATE: message truncated
[panos5:503587] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[panos5:503587] ***    and potentially your MPI job)

**Comment by HenningScheufler** [comment]
MultiDimAMR is only compatible with hex and wedges. So using it with snappyhexmesh does not work

**Comment by MitchellWhiting** [comment]
Okay, I thought since my snapphexMesh was making a hex mesh it would be fine, noted, thank you.
