### ISSUE TITLE
Problems when using the library for droplet evaporation cases

### ISSUE THREAD

**Issue by conradozanutto** [DLR-RY/TwoPhaseFlow#49]
Dear All,

We have started using the TwoPhaseFlow library to investigate droplet evaporation. Up to now, we have tried to simulate a simple case which is the evaporation of a static water droplet (gravity g = (0,0,0), with or without surface tension), in order to get familiarized with the code. This test case was proposed by Tanguy et al. (2007) (doi:10.1016/j.jcp.2006.07.003) in Section 4.1. However, in this regard, we have not had any success.

What we have noticed is that, for most of the tests, the implemented Hardt & Wondra model provides a positive source term inside the liquid and a negative source term inside the vapour, while it should provide the opposite for this droplet evaporation case. As a consequence, instead of the droplet evaporating, it is expanding (swelling), or, in other cases, nothing happens. We have gone through the code and tested several changes to it (pEqn.H, hardtWondra.C, hardtWondraGasPhase.C, alphaSuSp.H, implicitGrad.C, ...), because we thought it was some problem with the sign of some term, or with the way the source terms are added to the Poisson pressure equation or to the VOF equation, or the way the temperature gradients are calculated in the implicit and explicit models, or even some problem related to the interface normals. However, after several attempts, we are still getting the wrong results (we have used the code compiled with OpenFOAM v1812, v2106 and v2112).

We have tried to contact the contributors/users of this library (and also provided the test case and a schematic of it) to see if we are doing something wrong or if the models implemented in the code are not able to tackle this problem (thank you so much for those who have replied). We are going to implement new evaporation models based on concentration (mass fraction) gradient and also implement some activity and fugacity models to account for the non-ideality of the liquid and gas phases, to this library or others we have found in the literature.

Since, (most) probably, we are doing something wrong, I just would like to ask the library contributors/users, if you have been able to run droplet evaporation cases with this library? If yes, could you, please, share with us some test case in this regard, and also tell us the OpenFOAM version you have used?

Thank you so much for your attention and congratulations on this very nice library.

**Comment by HenningScheufler** [comment]
[staticDroplet.zip](https://github.com/DLR-RY/TwoPhaseFlow/files/13271368/staticDroplet.zip)

[Tanguy et al. ](https://paca.ime.usp.br/pluginfile.php/22535/mod_resource/content/0/TOPICO_06/menard2007.pdf)

I simplified the case to 2D and the solver behaves as expected. The saturation temperature is 373.15 K and the temperature of the drop is 353.15 K, resulting in condensation at the interface. In Fig 1a, the temperature of the droplet is about 313 K which would cause evaporation of the droplet.

The testcase(4.1. Vaporization of an axisymmetric static droplet (low temperature)) account for concentration-driven phase change, which is not accounted for in the solver.

**Comment by conradozanutto** [comment]
Hi Henning,

Regarding the test case presented by Tanguy et al. (2007) in Section 4.1 and which I shared with you, the droplet starts at a temperature of 80 degrees Celsius (353 K) and the surrounding air is at 100 degrees Celsius (373 K). So, the expected result is evaporation. The cooling of the droplet presented in Figure 1 (a) and in Figure 4, is exactly because of the evaporation process (due to the latent heat), and, as you can see in Figure 2, there is no expansion in the process, note that the normalized square diameter versus time just decreases over the evaporation process.

I could reproduce this test case in my paper, however, as you mentioned, I used an evaporation model based on concentration (mass fraction) gradient. However, in the evaporation model used by Tanguy et al., note that, in Equations 5, 6 and 7 of the paper, the temperature contribution directly appears in the estimation of the mass fraction at the vapour side, where they use the Clausius-Clapeyron equation to calculate the vapour pressure, so, the temperature dependence is taken into account. This is why, I think, the models implemented in TwoPhaseFlow are able to reproduce this, because (I think, I am not sure) if the temperature field is correctly captured for this case, the mass fraction would be correctly evaluated, since the mass fraction depends on the temperature.

I am running more tests to understand why it is not working and I am getting some interesting results. However, I have not been able to reproduce this test case yet. Maybe you are right, I need to implement a concentration-driven phase change model, what I intend to do next. What is really weird, in my opinion, is that the Hardt & Wondra model is providing a positive source term inside the liquid and a negative source term inside the vapour, while it should provide the opposite for this droplet evaporation case.

I have focused my tests on the two-field approach for temperature, the implicit model to evaluate the temperature gradient and the Hardt & Wondra model. If you have any suggestions about that, please, let me know.

Thank you so much for taking the time to answer us.

Kind regards,
Conrado

**Comment by HenningScheufler** [comment]
For a multicomponent systems the saturation temperature is a function of the concentration fields and the pressure. In the current implementation, this is not the case the saturation temperature is only a function of the pressure. If you lower TSat in phaseChangeProperties:

```
satProperties
{
    singleComponentSatProp function;
    Tmin 100.0;
    Tmax 500.0;
    pSat constant 1e5;
    TSat constant 373.15; // if you lower it to 314 you should get evaporation
    L constant 2.26e6;

}
```

With the specified values, TSat= 100C and Tliquid 80 C, the solver predicts condensation as expected.

**Comment by conradozanutto** [comment]
Hi Henning,

Thank you very much for sharing this.

Yes, I understand what you mean. By using the implemented models, I should not expect evaporation if a superheated liquid is not considered. I was trying to change the implementation to see if I could have evaporation with this test case without the need to implement new models, i.e. I was trying to change the already implemented models for this. However, I think you are right, the best is to consider and implement a concentration-driven phase change model, what I am currently doing.

Thank you!

Kind regards,
Conrado
